### ISSUE TITLE
Pas possible de s'inscrire sur le launcher

### ISSUE THREAD

**Issue by xxvirusxx6767** [MrDarkSkil/Launcher_Multigaming#49]
## Tell if it's a panel or launcher bug:
- [] Panel bug
- [X] Launcher bug

## Brief of your bug
Impossible de se créer un compte sur le launcher, il y à un problème.
Newtonsoft.Json.JsonReaderException : 'Error reading JObject from JsonReader. Path '', line 0, position 0.'
Ligne de code: 
`          dynamic res = JObject.Parse(content.ToString());
`
## Operating system
Windows 10

## Logs
```
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=Error reading JObject from JsonReader. Path '', line 0, position 0.
  Source=Newtonsoft.Json
  Arborescence des appels de procédure :
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at LauncherArma3.registerForm.registerButton_Click(Object sender, EventArgs e) in C:\Users\xnooztv\Desktop\Launcher_Multigaming-5.0\LauncherArma3\LauncherArma3\registerForm.cs:line 82
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at MaterialSkin.Controls.MaterialRaisedButton.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at LauncherArma3.loginForm.registerLink_Click(Object sender, EventArgs e) in C:\Users\xnooztv\Desktop\Launcher_Multigaming-5.0\LauncherArma3\LauncherArma3\loginForm.cs:line 541
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at MaterialSkin.Controls.MaterialRaisedButton.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at LauncherArma3.Program.Main() in C:\Users\xnooztv\Desktop\Launcher_Multigaming-5.0\LauncherArma3\LauncherArma3\Program.cs:line 45
```

**Comment by FlashModz** [comment]
Avez-vous par hasard tenté l'inscription tout en ayant le launcher lancé avec VS ?

**Comment by xxvirusxx6767** [comment]
Oui, j'ai essayer avec le debug de VS, et via le build, aucun des deux ne fonctionne..

**Comment by FlashModz** [comment]
Ok via le debug, normal, car selon certains environnements des problèmes peuvent survenir et via le build il faudrai vérifié les erreurs que tu à lors de la génération en build

**Comment by xxvirusxx6767** [comment]
Il n'y à aucune erreur justement :/

**Comment by FlashModz** [comment]
Je t'invite à venir sur le Discord ==> https://discord.gg/nbSATt

**Comment by MrDarkSkil** [comment]
Le bug à été fix avec le dernier push 😃 https://github.com/MrDarkSkil/Launcher_Multigaming/commit/28903b24125e0cf63701d46e14fa4b01a7f19326 

Vous n'avez qu'a changer ce fichier (api/register.php)
